### ISSUE TITLE
Error on rake on OSX

### ISSUE THREAD

**Issue by jadsonlourenco** [octohost/octohost-cookbook#11]
after installing when I try to run any rake command get this error:
```
jadson:octohost-cookbook jadson$ rake build_droplet --trace
rake aborted!
cannot load such file -- foodcritic
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jadson/www/octohost-cookbook/Rakefile:2:in `<top (required)>'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load_rakefile'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:637:in `raw_load_rakefile'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:94:in `block in load_rakefile'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:93:in `load_rakefile'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:77:in `block in run'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/Users/jadson/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/Users/jadson/.rbenv/versions/2.1.5/bin/rake:33:in `<main>'
```

**Comment by darron** [comment]
If you 'gem install foodcritic' that should fix it.

**Comment by jadsonlourenco** [comment]
get this one now: **LoadError: cannot load such file -- rspec/core/rake_task**

**Comment by jadsonlourenco** [comment]
ok the **gem install rspec** solve the last problem, but get other error, so in the end i quit. I've broken the head with Ruby sometimes ago and abandoned because of it. I really wanted to use your tool, but requires understanding Ruby just to be able to install, I wonder how will the maintenance later. But it's a great tool, much like Deis (which is more complex and managed to install, but ideal for production).

Thank you @darron!

**Comment by darron** [comment]
If you've done a `bundle install` - that should all be taken care of.
